package main_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestParseFlags(t *testing.T) {
	// We test flag parsing indirectly by running the binary with various args
	// and checking exit codes / stderr output.
	// Direct unit tests would require exporting parseFlags; instead we test
	// the full binary behavior which also covers integration.
}

func buildBinary(t *testing.T) string {
	t.Helper()
	binary := filepath.Join(t.TempDir(), "legogen")
	cmd := exec.Command("go", "build", "-o", binary, ".")
	cmd.Dir = filepath.Join(mustGetwd(t), ".")
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("failed to build legogen: %v\n%s", err, out)
	}
	return binary
}

func mustGetwd(t *testing.T) string {
	t.Helper()
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	return wd
}

func TestCLIErrors(t *testing.T) {
	binary := buildBinary(t)

	tests := []struct {
		name      string
		args      []string
		env       map[string]string
		wantError string
	}{
		{
			name:      "no flags",
			args:      nil,
			wantError: "-type is required",
		},
		{
			name:      "type without operation",
			args:      []string{"-type", "Foo"},
			env:       map[string]string{"GOPACKAGE": "mypkg"},
			wantError: "at least one operation flag is required",
		},
		{
			name:      "unknown equal strategy",
			args:      []string{"-type", "Foo", "-equal", "unknown"},
			env:       map[string]string{"GOPACKAGE": "mypkg"},
			wantError: "unknown -equal strategy",
		},
		{
			name:      "empty type after star",
			args:      []string{"-type", "*", "-equal", "viewer"},
			env:       map[string]string{"GOPACKAGE": "mypkg"},
			wantError: "-type must specify a type name",
		},
		{
			name:      "no package",
			args:      []string{"-type", "Foo", "-equal", "comparer"},
			wantError: "package name not found",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cmd := exec.Command(binary, tt.args...)
			cmd.Dir = t.TempDir()
			// Clear GOPACKAGE from env to avoid inheriting it.
			cmd.Env = append(os.Environ(), "GOPACKAGE=")
			for k, v := range tt.env {
				cmd.Env = append(cmd.Env, k+"="+v)
			}
			out, err := cmd.CombinedOutput()
			if err == nil {
				t.Fatalf("expected error, got success; output: %s", out)
			}
			if !strings.Contains(string(out), tt.wantError) {
				t.Errorf("expected error containing %q, got: %s", tt.wantError, out)
			}
		})
	}
}

func TestGenerate(t *testing.T) {
	binary := buildBinary(t)

	tests := []struct {
		name         string
		args         []string
		pkg          string
		wantContains []string
	}{
		{
			name: "comparer value type",
			args: []string{"-type", "ExampleView", "-equal", "comparer"},
			pkg:  "mypkg",
			wantContains: []string{
				"// Code generated by legogen; DO NOT EDIT.",
				"package mypkg",
				`import "github.com/krelinga/go-lego"`,
				"func (e ExampleView) Equal(other ExampleView) bool {",
				"lego.EqualComparer(e, other)",
			},
		},
		{
			name: "viewer pointer type",
			args: []string{"-type", "*Example", "-equal", "viewer"},
			pkg:  "mypkg",
			wantContains: []string{
				"package mypkg",
				"func (e *Example) Equal(other *Example) bool {",
				"lego.EqualViewer(e, other)",
			},
		},
		{
			name: "slice value type",
			args: []string{"-type", "ExampleSliceView", "-equal", "slice"},
			pkg:  "mypkg",
			wantContains: []string{
				"func (e ExampleSliceView) Equal(other ExampleSliceView) bool {",
				"lego.EqualSlice(e, other)",
			},
		},
		{
			name: "slicego value type",
			args: []string{"-type", "IntSlice", "-equal", "slicego"},
			pkg:  "mypkg",
			wantContains: []string{
				"func (i IntSlice) Equal(other IntSlice) bool {",
				"lego.EqualSliceGo(i, other)",
			},
		},
		{
			name: "in lego package no import",
			args: []string{"-type", "Foo", "-equal", "comparer"},
			pkg:  "lego",
			wantContains: []string{
				"package lego",
				"EqualComparer(f, other)",
			},
		},
		{
			name: "custom output file",
			args: []string{"-type", "Foo", "-equal", "comparer", "-output", "custom.go"},
			pkg:  "mypkg",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := t.TempDir()
			cmd := exec.Command(binary, tt.args...)
			cmd.Dir = dir
			cmd.Env = append(os.Environ(), "GOPACKAGE="+tt.pkg)
			out, err := cmd.CombinedOutput()
			if err != nil {
				t.Fatalf("legogen failed: %v\n%s", err, out)
			}

			// Determine expected output file.
			outputFile := ""
			for i, a := range tt.args {
				if a == "-output" && i+1 < len(tt.args) {
					outputFile = tt.args[i+1]
				}
			}
			if outputFile == "" {
				typeName := ""
				for i, a := range tt.args {
					if a == "-type" && i+1 < len(tt.args) {
						typeName = strings.TrimPrefix(tt.args[i+1], "*")
					}
				}
				outputFile = strings.ToLower(typeName) + "_legogen.go"
			}

			content, err := os.ReadFile(filepath.Join(dir, outputFile))
			if err != nil {
				t.Fatalf("output file not found: %v", err)
			}

			for _, want := range tt.wantContains {
				if !strings.Contains(string(content), want) {
					t.Errorf("output missing %q\n\ngot:\n%s", want, content)
				}
			}
		})
	}
}

func TestGenerateInLegoPackage(t *testing.T) {
	binary := buildBinary(t)
	dir := t.TempDir()
	cmd := exec.Command(binary, "-type", "Foo", "-equal", "comparer")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOPACKAGE=lego")
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("legogen failed: %v\n%s", err, out)
	}

	content, err := os.ReadFile(filepath.Join(dir, "foo_legogen.go"))
	if err != nil {
		t.Fatalf("output file not found: %v", err)
	}

	// Should NOT have import when generating inside lego package.
	if strings.Contains(string(content), `import`) {
		t.Errorf("should not have import in lego package, got:\n%s", content)
	}
}
