package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strings"
	"text/template"
	"unicode"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "legogen: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	cfg, err := parseFlags(os.Args[1:])
	if err != nil {
		return err
	}
	return generate(cfg)
}

type config struct {
	Package     string
	TypeName    string
	ReceiverVar string
	IsPointer   bool
	Output      string
	Equal       string // comparer, viewer, slice, slicego
}

func parseFlags(args []string) (config, error) {
	fs := flag.NewFlagSet("legogen", flag.ContinueOnError)
	typeName := fs.String("type", "", "target type name (prefix with * for pointer receiver)")
	equal := fs.String("equal", "", "equal strategy: comparer, viewer, slice, slicego")
	output := fs.String("output", "", "output file name (default: <type>_legogen.go)")
	pkg := fs.String("pkg", "", "package name (default: $GOPACKAGE)")

	if err := fs.Parse(args); err != nil {
		return config{}, err
	}

	if *typeName == "" {
		return config{}, fmt.Errorf("-type is required")
	}

	if *equal == "" {
		return config{}, fmt.Errorf("at least one operation flag is required (e.g. -equal)")
	}

	switch *equal {
	case "comparer", "viewer", "slice", "slicego":
	default:
		return config{}, fmt.Errorf("unknown -equal strategy %q; must be one of: comparer, viewer, slice, slicego", *equal)
	}

	isPointer := strings.HasPrefix(*typeName, "*")
	cleanType := strings.TrimPrefix(*typeName, "*")
	if cleanType == "" {
		return config{}, fmt.Errorf("-type must specify a type name")
	}

	pkgName := *pkg
	if pkgName == "" {
		pkgName = os.Getenv("GOPACKAGE")
	}
	if pkgName == "" {
		return config{}, fmt.Errorf("package name not found: set $GOPACKAGE (via go generate) or use -pkg flag")
	}

	outputFile := *output
	if outputFile == "" {
		outputFile = strings.ToLower(cleanType) + "_legogen.go"
	}

	receiverVar := string(unicode.ToLower([]rune(cleanType)[0]))

	return config{
		Package:     pkgName,
		TypeName:    cleanType,
		ReceiverVar: receiverVar,
		IsPointer:   isPointer,
		Output:      outputFile,
		Equal:       *equal,
	}, nil
}

// receiverType returns the full receiver type string, e.g. "*Example" or "ExampleView".
func (c config) receiverType() string {
	if c.IsPointer {
		return "*" + c.TypeName
	}
	return c.TypeName
}

func generate(cfg config) error {
	var buf bytes.Buffer

	// Header
	fmt.Fprintf(&buf, "// Code generated by legogen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", cfg.Package)

	// Determine if we need the lego import.
	// When the generated code is inside the lego package itself, no import is needed.
	needsImport := cfg.Package != "lego"
	if needsImport {
		fmt.Fprintf(&buf, "import \"github.com/krelinga/go-lego\"\n\n")
	}

	// Generate Equal method
	methodSrc, err := generateEqual(cfg)
	if err != nil {
		return fmt.Errorf("generating Equal: %w", err)
	}
	buf.WriteString(methodSrc)

	// Format
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Write unformatted as fallback so the user can debug.
		fmt.Fprintf(os.Stderr, "legogen: warning: generated code failed gofmt: %v\n", err)
		formatted = buf.Bytes()
	}

	return os.WriteFile(cfg.Output, formatted, 0644)
}

var equalTemplates = template.Must(template.New("").Parse(""))

func init() {
	for name, body := range equalTemplateBodies {
		template.Must(equalTemplates.New(name).Parse(body))
	}
}
